name = "SquareSymmetries"
uuid = "782ece98-c869-49e9-9e53-16c5dacb9be9"
license = "MIT"
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
